package org.iu.engrcloudcomputing.mapreduce.hadoop.manager.impl;

import com.google.api.services.compute.model.Metadata;
import com.google.protobuf.ProtocolStringList;
import io.grpc.ManagedChannel;
import org.iu.engrcloudcomputing.mapreduce.hadoop.autogenerated.BeginMapReduceGrpc;
import org.iu.engrcloudcomputing.mapreduce.hadoop.autogenerated.Master;
import org.iu.engrcloudcomputing.mapreduce.hadoop.exception.MapReduceFailureException;
import org.iu.engrcloudcomputing.mapreduce.hadoop.helper.Constants;
import org.iu.engrcloudcomputing.mapreduce.hadoop.helper.GoogleComputeOps;
import org.iu.engrcloudcomputing.mapreduce.hadoop.manager.spi.HadoopManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.lang.invoke.MethodHandles;
import java.security.GeneralSecurityException;
import java.util.ArrayList;
import java.util.List;

public class HadoopManagerImpl implements HadoopManager {

    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass().getSimpleName());

    private static final String STARTUP_SCRIPT_URL_KEY = "startup-script-url";
    private static final String STARTUP_SCRIPT_URL_VALUE = "gs://" + Constants.PROJECT_ID + "/vm_startup.sh";
    private static final String COMPONENT_NAME_KEY = "component";
    private static final String KV_STORE_KEY = "kv-store";
    private static final String MASTER_DETAILS_KEY = "master";
    private static final String UUID_KEY = "uuid";
    private static final String SCRIPT_KEY = "script";
    private static final String script = "run_master.sh";

    @Override
    public String initiateCluster(String componentName, int port) throws IOException, GeneralSecurityException {

        int status = -1;
        GoogleComputeOps gc = new GoogleComputeOps(componentName);

        while (status != 0) {
            status = gc.startInstance(getMetaData(componentName, componentName, port),
                    false);
        }

        return gc.getIpAddressOfInstance();
    }

    @Override
    public List<String> runMapReduce(ManagedChannel channel, String kvStoreIpAddress, int kvStorePort, String masterIpAddress,
                                     int masterPort, int mapperCount, int reducerCount, String mapperJar, String reducerJar,
                                     String initialKey) {

        BeginMapReduceGrpc.BeginMapReduceBlockingStub blockingStub = BeginMapReduceGrpc.newBlockingStub(channel);

        Master.MapReduceResponse mapReduceResponse = blockingStub.mapReduce(Master.MapReduceParams.newBuilder().setInitialKey(initialKey)
                .setMapperJar(mapperJar)
                .setMappers(mapperCount)
                .setReducerJar(reducerJar)
                .setReducers(reducerCount)
                .setKvStoreIpAddress(kvStoreIpAddress)
                .setMasterIpAddress(masterIpAddress)
                .setMasterPort(masterPort)
                .setKvStorePort(kvStorePort).build());

        Master.Message message = mapReduceResponse.getMessage();

        int responseCode = message.getResponseCode();
        if (responseCode != 200) {
            LOGGER.error("MapReduce task failed with status: {}", responseCode);
            throw new MapReduceFailureException("Map Reduce Task failed");
        }

        ProtocolStringList keyList = mapReduceResponse.getKeys().getKeyList();
        LOGGER.info("Map Reduce Task was successful ");

        return new ArrayList<>(keyList);
    }

    @Override
    public boolean destroyCluster(String componentName, String ipAddress, int port) {

        LOGGER.info("Shutting down the master running on the ipAddress: {}, port: {}", ipAddress, port);

        int status = -1;
        GoogleComputeOps gc = new GoogleComputeOps(componentName);

        while (status != 0) {
            status = gc.deleteInstance();
        }

        return true;
    }

    private Metadata getMetaData(String uuid, String componentName, int port) {

        Metadata metadata = new Metadata();
        List<Metadata.Items> itemsList = new ArrayList<>();
        itemsList.add(getItem(STARTUP_SCRIPT_URL_KEY, STARTUP_SCRIPT_URL_VALUE));
        itemsList.add(getItem(KV_STORE_KEY, ".:"));
        itemsList.add(getItem(MASTER_DETAILS_KEY, ".:" + port));
        itemsList.add(getItem(UUID_KEY, uuid));
        itemsList.add(getItem(COMPONENT_NAME_KEY, componentName));
        itemsList.add(getItem(SCRIPT_KEY, script));
        metadata.setItems(itemsList);
        return metadata;
    }

    private Metadata.Items getItem(String key, String value) {
        Metadata.Items item = new Metadata.Items();
        item.setKey(key);
        item.setValue(value);

        return item;
    }
}
